### ISSUE TITLE
[Feature] Zendesk Customer Metrics Model

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_zendesk#160]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Merge in this [branch](https://github.com/fivetran/dbt_zendesk/blob/explore/customer-metrics-model/models/zendesk__customer_metrics.sql) after feedback from customers on the new model.  If anyone is interested in testing:
```yml
# packages.yml
packages:
- git: https://github.com/fivetran/dbt_zendesk.git
  revision: explore/customer-metrics-model
```

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.
