### ISSUE TITLE
BUG - resources exceeded error caused by an order by

### ISSUE THREAD

**Issue by MarkMacArdle** [fivetran/dbt_zendesk#31]
**Are you a current Fivetran customer?** 
Mark MacArdle, Bought by Many

**Describe the bug**
An `order by` in the `stg_zendesk__ticket_field_history` model is causing a resources exceed error

**Steps to reproduce**

**Expected behavior**

**Project variables configuration**

```yml
copy dbt_project.yml here
```

**Package Version**
```yml
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.4  # dbt recommend pinning all packages, `*` doesn't work.

  # will also import fivetran/zendesk_source as a dependency
  - package: fivetran/zendesk
    version: 0.4.1
```

**Warehouse**

 
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 

low

**Are you interested in contributing to this package?** 

- [x] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
