### ISSUE TITLE
BUG - Dependency resolution issue with dbt 0.20

### ISSUE THREAD

**Issue by msluyter** [fivetran/dbt_zendesk#38]
**Are you a current Fivetran customer?** 
Yes; Mike Sluyter, Software Engineer at GetUpside

**Describe the bug**
Dependency resolution fails with `fivetran/zendesk` == 0.5.2 and `fivetran/zendesk_source` >= 0.4.0 with the following error:

```
❯ ./dbt deps
Running with dbt=0.20.0
Encountered an error:
Version error for package fivetran/zendesk_source: Could not find a satisfactory version from options: ['>=0.4.0', '<0.5.0', '>=0.3.0', '<0.4.0']
```

It looks like the problem is that this package depends on an older version of `zendesk_source` causing a conflict. I drew a picture:

```
         ┌────────┐                                  
         │  Dbt   ├─────────────────────┐            
         │ 0.20.0 │                     │            
         └───┬────┘                     │            
             │                          │            
             │                          │            
             │                          │            
   ┌─────────▼─────────┐   ┌────────────▼───────────┐
   │ fivetran/zendesk  │   │fivetran/zendesk_source │
   │        5.2        │   │         >= 4.0         │
   └─────────┬─────────┘   └────────────────────────┘
             │                                       
             │                                       
             │                                       
             │                                       
┌────────────▼────────────┐                          
│ fivetran/zendesk_source │                          
│  [">=0.3.0","<0.4.0"]   │                          
└─────────────────────────┘                          
```
I tried just removing the explicit dependency on zendesk_source, but that resulted in other conflicts with `fivetran_utils`:

```
❯ ./dbt deps
Running with dbt=0.20.0
Encountered an error:
Version error for package fivetran/fivetran_utils: Could not find a satisfactory version from options: ['>=0.2.0', '<0.3.0', '>=0.2.0', '<0.3.0', '>=0.1.0', '<0.2.0']
```

**Steps to reproduce**
1. run `dbt deps` with packages illustrated below.

**Expected behavior**
Dependencies successfully resolved.

**Project variables configuration**

Non relevant variables omitted:
```yml
vars:
    zendesk_source:
        zendesk_database: raw
        zendesk_schema: fivetran__zendesk
    hubspot_source:
        hubspot_database: raw
        hubspot_schema: fivetran__hubspot
    # disable a few Hubspot models that cause errors
    hubspot_email_event_forward_enabled: false
    hubspot_email_event_print_enabled: false
    hubspot_engagement_call_enabled: false
```

**Package Version**

```yml
  - package: fivetran/hubspot
    version: 0.4.0
  - package: fivetran/hubspot_source
    version: 0.4.0
  - package: fivetran/zendesk
    version: 0.5.2
  - package: fivetran/zendesk_source
    version: [">=0.4.0", "<0.5.0"]
```

**Warehouse**
- [ ] BigQuery
- [ ] Redshift
- [x] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
I'm guessing that this PR resolves the issue: https://github.com/fivetran/dbt_zendesk/pull/37 If that's the case, can you us know and when you think that'll get merged and a new version released?

**Screenshots**

**Please indicate the level of urgency** 
Medium High -- we're trying to update dbt to fix an unrelated issue we're having that's causing our CI/CD runs to fail.

**Are you interested in contributing to this package?** 
- [ ] Yes, I can do this and open a PR for your review.
- [x] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
