### ISSUE TITLE
BUG - Too many partitions produced by query, allowed 4000, query produces at least 4272 partitions

### ISSUE THREAD

**Issue by csaroff** [fivetran/dbt_zendesk#39]
**Are you a current Fivetran customer?** 
Yes; Chaskin Saroff, Data Engineer at Bstock

**Describe the bug**
Too many partitions produced by `int_zendesk__field_calendar_spine` and `int_zendesk__field_history_pivot`.

```bash
Database Error in model int_zendesk__field_calendar_spine (models/ticket_history/int_zendesk__field_calendar_spine.sql)
  Too many partitions produced by query, allowed 4000, query produces at least 4272 partitions
  compiled SQL at target/run/zendesk/models/ticket_history/int_zendesk__field_calendar_spine.sql

Database Error in model int_zendesk__field_history_pivot (models/ticket_history/int_zendesk__field_history_pivot.sql)
  Too many partitions produced by query, allowed 4000, query produces at least 4022 partitions
  compiled SQL at target/run/zendesk/models/ticket_history/int_zendesk__field_history_pivot.sql
```

**Steps to reproduce**
Have more than 4000 days worth of field history data in zendesk while using bigquery as your data warehouse.

**Expected behavior**
No error should occur.

**Project variables configuration**
```yml

# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'bstock'
version: '0.0.1'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
models:
  +persist_docs:
    relation: true
    columns: true
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the marketplace/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  marketplace:
      # Applies to all files under models/marketplace/
      marketplace:
          materialized: table


vars:
    'dbt_date:time_zone': 'America/Los_Angeles'
```

**Package Version**
```yml
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.4
  - package: fivetran/zendesk
    version: 0.4.0
  - package: fivetran/salesforce
    version: 0.3.1
  - package: fishtown-analytics/spark_utils
    version: 0.1.0
  - package: calogica/dbt_date
    version: 0.2.5
```

**Warehouse**
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Please indicate the level of urgency** 
Not urgent, but the bug is frustrating because my build fails constantly if I leave this package installed.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [x] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by csaroff** [comment]
It might not hurt to simply ignore data that is more than 4000 days old if the data warehouse is bigquery.

**Comment by fivetran-jamie** [comment]
hey there @csaroff -- you can expect a more formal solution released in the next week or so, but for the time being, this branch of the package should hopefully work for you without having to exclude any data
```yml
# packages.yml
  - git: https://github.com/fivetran/dbt_zendesk.git
    revision: bq-partitions
    warn-unpinned: false  
```

basically, i just changed the [granularity](https://github.com/fivetran/dbt_zendesk/blob/bq-partitions/models/ticket_history/int_zendesk__field_calendar_spine.sql#L4) of the `partition_by` clause to `week`. the final solution may be different, but let me know if this works for you!

**Comment by fivetran-jamie** [comment]
^ did this work for you btw? @csaroff

**Comment by csaroff** [comment]
@fivetran-jamie I haven't gotten a chance to try it out yet, but will try soon and let you know. Thanks!

**Comment by csaroff** [comment]
@fivetran-jamie Looks like there might be a bug with this.

Here's what I'm seeing when I do a `dbt run`

```python
Completed with 2 errors and 0 warnings:

Database Error in model int_zendesk__field_calendar_spine (models/ticket_history/int_zendesk__field_calendar_spine.sql)
  PARTITION BY expression must be DATE(<timestamp_column>), DATE(<datetime_column>), DATETIME_TRUNC(<datetime_column>, DAY/HOUR/MONTH/YEAR), a DATE column, TIMESTAMP_TRUNC(<timestamp_column>, DAY/HOUR/MONTH/YEAR), DATE_TRUNC(<date_column>, MONTH/YEAR), or RANGE_BUCKET(<int64_column>, GENERATE_ARRAY(<int64_value>, <int64_value>[, <int64_value>]))
  compiled SQL at target/run/zendesk/models/ticket_history/int_zendesk__field_calendar_spine.sql

Database Error in model int_zendesk__field_history_pivot (models/ticket_history/int_zendesk__field_history_pivot.sql)
  PARTITION BY expression must be DATE(<timestamp_column>), DATE(<datetime_column>), DATETIME_TRUNC(<datetime_column>, DAY/HOUR/MONTH/YEAR), a DATE column, TIMESTAMP_TRUNC(<timestamp_column>, DAY/HOUR/MONTH/YEAR), DATE_TRUNC(<date_column>, MONTH/YEAR), or RANGE_BUCKET(<int64_column>, GENERATE_ARRAY(<int64_value>, <int64_value>[, <int64_value>]))
  compiled SQL at target/run/zendesk/models/ticket_history/int_zendesk__field_history_pivot.sql
  ```
  
Looks like the same error is showing on your [circleci build](https://app.circleci.com/pipelines/github/fivetran/dbt_zendesk/152/workflows/2ec2fffb-00f0-4d73-8e13-d3a9c38a3df7/jobs/154?invite=true#step-107-201) for that branch.

**Comment by fivetran-jamie** [comment]
@csaroff ack somehow missed the circle error 🤦 it _should_ be working now -- `week` is not actually a supported granularity level so switched it to `month`

**Comment by csaroff** [comment]
No worries. I'll try again today. Thanks!

**Comment by csaroff** [comment]
Looks like it cleared up the previous error, but now I'm getting:

```python
Database Error in model int_zendesk__field_calendar_spine (models/ticket_history/int_zendesk__field_calendar_spine.sql)
  Query exceeded resource limits. This query used 19447 CPU seconds but would charge only 15M Analysis bytes. This exceeds the ratio supported by the on-demand pricing model. Please consider moving this workload to the flat-rate reservation pricing model, which does not have this limit. 19447 CPU seconds were used, and this query must use less than 3800 CPU seconds.
  compiled SQL at target/run/zendesk/models/ticket_history/int_zendesk__field_calendar_spine.sql
```

**Comment by fivetran-jamie** [comment]
Ah shoot -- and are you trying to run a full refresh? 

Also it might be more efficient to troubleshoot this over a call if you'd like! You can book an office hours session [here](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours?month=2021-09) if that sounds good

**Comment by fivetran-jamie** [comment]
oh one idea .... this may be because `int_zendesk__calendar_spine` is ephemeral by default (so that whole model is just a CTE in `int_zendesk__field_calendar_spine`). could you try adding the following to your dbt_project.yml? 
```
models: 
    zendesk:
        utils:
            +materialized: table
```
