### ISSUE TITLE
BUG - int_zendesk__calendar_spine doesn't use `zendesk_intermediate` schema

### ISSUE THREAD

**Issue by wuservices** [fivetran/dbt_zendesk#46]
**Are you a current Fivetran customer?** 
Jon Wu, Architect, Paper Culture

**Describe the bug**
`int_zendesk__calendar_spine` model is not created in the `zendesk_intermediate` schema like the other intermediate models.

**Steps to reproduce**
1. `dbt run`
2. Check schema

**Expected behavior**
`int_zendesk__calendar_spine` uses `zendesk_intermediate`

**Project variables configuration**
N/A

**Package Version**

```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.3
  - package: fivetran/ad_reporting
    version: 0.4.0
  - package: fivetran/facebook_ads
    version: 0.3.0
  - package: fivetran/google_ads
    version: 0.3.1
  - package: fivetran/microsoft_ads
    version: 0.3.0
  - package: fivetran/pinterest
    version: 0.4.0
  - package: fivetran/zendesk
    version: 0.6.0

```

**Warehouse**

 
- [X] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 
I believe this happens because this model is in the utils folder and thus doesn't pick up the intermediate config from `dbt_project.yml`. I'd fix but wasn't sure the best way to handle given how you set things up, and am assuming it's just a quick config change in the file.

**Screenshots**
![image](https://user-images.githubusercontent.com/190434/135177442-ba72086c-fbdd-49b1-a4df-e9481c739c24.png)

**Please indicate the level of urgency** 

Nice to have. We share final model datasets with users, and hide intermediate and staging models from them so they can get straight to the action.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [X] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Hey @wuservices thanks for opening this issue!

It looks like we do not designate the schema as it is materialized as ephemeral by default
https://github.com/fivetran/dbt_zendesk/blob/fc30839a4bbf781ee11ff35ba99ab791bc7b4fcf/dbt_project.yml#L26

What you could do to update this on your end is by adding a `+schema` configuration to your models config so the calendar spine will write to the same intermediate schema in the meantime.
```yml
models:
  zendesk:
    utils:
      +materialized: table
      +schema: zendesk_intermediate
```
Otherwise we will update this on our end in the next release of this package to account for users that materialize this model as a table or view!
