### ISSUE TITLE
BUG - SLA_policies model doesn't have correct is_sla_breach

### ISSUE THREAD

**Issue by jackiexsun** [fivetran/dbt_zendesk#51]
**Are you a current Fivetran customer?** 
I work at Fivetran :) 

**Describe the bug**
zendesk__sla_policies doesn't always correctly identify SLA breaches (missed SLAs). 

**Steps to reproduce**
For example ticket_id = 18717 
```
select *
from `digital-arbor-400.dbt_pkg_zendesk.zendesk__sla_policies`
where metric = 'first_reply_time' and sla_policy_name in ('Enterprise SLA - Support', 'Standard/Starter SLA - Support') and is_sla_breach and ticket_id = 18717
```
is breached but in Zendesk, it is achieved 
<img width="1003" alt="Screen Shot 2021-10-27 at 2 59 22 PM" src="https://user-images.githubusercontent.com/38146057/139153429-5d422816-1b9f-4ccc-8adb-ea1451da681f.png">

Other ticket_id's where is_sla_breach is true when it should be false (these are all "first_reply_time" metrics)
19505
19539
19544
<img width="987" alt="Screen Shot 2021-10-27 at 3 01 04 PM" src="https://user-images.githubusercontent.com/38146057/139153608-35f1ffcf-8e4b-4888-8c5b-4fdee13ccb3d.png">

**Expected behavior**

**Project variables configuration**

```
name: 'prj_production'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'fivetran'

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

on-run-start:
    - '{{create_udfs()}}' # Hook that executes macro to create UDFs on run start (look inside the macros folder)

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  +persist_docs:
      relation: true
      columns: true
  prj_production:
      materialized: view
  zendesk:
    +schema: 'dbt_pkg_zendesk'
  zendesk_source:
    +schema: 'dbt_pkg_zendesk'

# This section is used for variables for dbt packages
vars: 
  zendesk_source:
    zendesk_schema: zendesk_new
    using_schedules: false        # Disable if you do not have the schedule and ticket_schedule tables, or if you do not want metrics reported in business hours
  zendesk:
    using_schedules: false        # Disable if you do not have the schedule and ticket_schedule tables, or if you do not want metrics reported in business hours

```

**Package Version**

```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.6
  - git: https://github.com/fivetran/dbt_zendesk.git
    # TODO once the production version zendesk package incremental strategy is verified, we need to swap back to that version
    revision: fix/no-incremental-field-history
    warn-unpinned: false
  - package: fivetran/github
    version: [">=0.2.0", "<0.3.0"]
```

**Warehouse**

 
- [ x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 
We're currently recalculating SLA policy achievement metrics ourselves, but we'd like to transition to use the package if possible. We'll transition to use it as soon as it is accurate.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ x] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
