### ISSUE TITLE
BUG - First Reply Time metrics have mismatches

### ISSUE THREAD

**Issue by alexei-colvin** [fivetran/dbt_zendesk#53]
**Are you a current Fivetran customer?** 
Yes. My name is Alexei, Analytics Engineer working at Colvin.

**Describe the bug**
The metrics First Reply Time for both, business hours and calendar hours, are having different numbers compared to the Fivetran UI for the same ticket ids.

**Steps to reproduce**
1. Go to Zendesk queries editor. Select ticket_id as row, select First Reply Time - Business Hours and First Reply Time - Calendar hours as metric.
2. Go to the dbt output table zendesk__ticket_metrics and query for the same metrics and the same ticket_ids.
3. The numbers for First Reply Time don't match.

**Expected behavior**
The numbers of the table zendesk__ticket_metrics should match with the Zendesk UI numbers.

**Project variables configuration**
```yml
name: 'dbt_customer_experience'
version: '1.0.0'
config-version: 2

profile: 'customer_experience'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  zendesk:
    using_organization_tags: False
  zendesk_source:
    zendesk_database: thecolvin-data
    zendesk_schema: fivetran_zendesk


models:
  dbt_customer_experience:
    sources:
        materialized: ephemeral
    staging:
        schema: staging

  zendesk:
    +schema: staging    
    intermediate:
      +schema: staging
    sla_policy:
      +schema: staging
      materialized: view
    ticket_history:
      +schema: staging
      materialized: view
  zendesk_source:
    +schema: staging
    materialized: view
```

**Package Version**

```yml
packages:
  - package: fivetran/zendesk
    version: 0.7.0
```

**Warehouse**
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
In the screenshots you can see the mismatches and the workaround to fix the problem in calendar hours. **But we need also a solution for Business hours.**

**Screenshots**
![mismatches](https://user-images.githubusercontent.com/82418998/142626167-46882edd-65e7-420f-a170-532c5556f121.png)

![506166](https://user-images.githubusercontent.com/82418998/142626184-211f4600-106a-4cda-ad91-6428905e956a.png)

![506174](https://user-images.githubusercontent.com/82418998/142626192-db115506-fae5-468e-b70f-a24fb818ebdb.png)

**Please indicate the level of urgency** 
The metrics are not matching with the Zendesk UI. The stakeholders are being affected in analysis and decision making.

**Are you interested in contributing to this package?** 
- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [x] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
