### ISSUE TITLE
BUG - Requester Wait Time metrics have mismatches

### ISSUE THREAD

**Issue by alexei-colvin** [fivetran/dbt_zendesk#54]
**Are you a current Fivetran customer?** 
Yes. My name is Alexei, Analytics Engineer working at Colvin.

**Describe the bug**
The metric Requester Wait Time is having different numbers compared to the Fivetran UI for the same ticket ids.

**Steps to reproduce**
1. Go to Zendesk queries editor. Select ticket_id as row, select Requester Wait Time - Business Hours and Requester Wait Time - Calendar hours as metric.
2. Go to the dbt output table zendesk__ticket_metrics and query for the same metrics and the same ticket_ids.
3. The numbers for Requester Wait Time don't match.

**Expected behavior**
The numbers of the table zendesk__ticket_metrics should match with the Zendesk UI numbers.

**Project variables configuration**

```yml
name: 'dbt_customer_experience'
version: '1.0.0'
config-version: 2

profile: 'customer_experience'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  zendesk:
    using_organization_tags: False
  zendesk_source:
    zendesk_database: thecolvin-data
    zendesk_schema: fivetran_zendesk


models:
  dbt_customer_experience:
    sources:
        materialized: ephemeral
    staging:
        schema: staging

  zendesk:
    +schema: staging    
    intermediate:
      +schema: staging
    sla_policy:
      +schema: staging
      materialized: view
    ticket_history:
      +schema: staging
      materialized: view
  zendesk_source:
    +schema: staging
    materialized: view
```

**Package Version**

```yml
packages:
  - package: fivetran/zendesk
    version: 0.7.0
```

**Warehouse**

 
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
See the screenshots

**Screenshots**

![requester wait time](https://user-images.githubusercontent.com/82418998/143024530-c14ac6c7-8d8b-448c-b2a1-e357ed858092.png)

**Please indicate the level of urgency** 
The metrics are not matching with the Zendesk UI. The stakeholders are being affected in analysis and decision making.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [x] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
