### ISSUE TITLE
[Bug] < int_zendesk__schedule_spine > may be missing rows after DT ends

### ISSUE THREAD

**Issue by jflatter** [fivetran/dbt_zendesk#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I have spent a good deal of time trying to figure out why the table sla_policy only has rows as recent as Oct 30 2022.

After digging, I found the intermediate table called int_zendesk__schedule_spine, which only has rows with values for "valid until" up to Oct 30 2022 as well.  All other tables have seemingly valid data such as "sla policty applied" and "time zones".

Anyone else experiencing this issue?

### Expected behavior

I expect the model to give rows for all recently applied SLAs in the transformed table zendesk__sla_policies.

### dbt Project configurations
```yml
vars:
    #Shopify Vars
    shopify_union_schemas: ['shopify_tbv','shopify_tel','shopify_tna']

    #Zendesk Vars
    #using_schedules:            False         #Disable if you are not using schedules
    #using_domain_names:         False         #Disable if you are not using domain names
    using_user_tags:            False         #Disable if you are not using user tags
    #using_ticket_form_history:  False         #Disable if you are not using ticket form history
    #using_organization_tags:    False         #Disable if you are not using organization tags
```
### Package versions

packages:
  - package: fivetran/shopify
    version: [">=0.6.0", "<0.7.0"]
  - package: fivetran/netsuite
    version: [">=0.6.0", "<0.7.0"]
  - package: fivetran/zendesk
    version: [">=0.9.0", "<0.10.0"]

### What database are you using dbt with?

bigquery

### dbt Version

version: '1.0.0'

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.
